"""Add phase 2 JSON columns

Revision ID: 659b6e8212a6
Revises: eab328d9b384
Create Date: 2026-02-23 12:52:28.048476

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '659b6e8212a6'
down_revision: Union[str, None] = 'eab328d9b384'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tailor_sessions', sa.Column('contact_info_out', sa.Text(), nullable=True))
    op.add_column('tailor_sessions', sa.Column('summary_out', sa.Text(), nullable=True))
    op.add_column('tailor_sessions', sa.Column('experience_out', sa.Text(), nullable=True))
    op.add_column('tailor_sessions', sa.Column('education_out', sa.Text(), nullable=True))
    op.add_column('tailor_sessions', sa.Column('skills_out', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tailor_sessions', 'skills_out')
    op.drop_column('tailor_sessions', 'education_out')
    op.drop_column('tailor_sessions', 'experience_out')
    op.drop_column('tailor_sessions', 'summary_out')
    op.drop_column('tailor_sessions', 'contact_info_out')
    # ### end Alembic commands ###
