"""initial_schema

Revision ID: eab328d9b384
Revises: 
Create Date: 2026-02-18 12:35:59.541382

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eab328d9b384'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tailor_sessions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=True),
    sa.Column('resume_snippet', sa.Text(), nullable=True),
    sa.Column('job_title_hint', sa.String(), nullable=True),
    sa.Column('bullets_output', sa.Text(), nullable=True),
    sa.Column('keywords_output', sa.Text(), nullable=True),
    sa.Column('cover_letter_out', sa.Text(), nullable=True),
    sa.Column('provider_used', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tailor_sessions_user_id'), 'tailor_sessions', ['user_id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('device_id', sa.String(), nullable=False),
    sa.Column('is_pro', sa.Boolean(), nullable=True),
    sa.Column('monthly_uses', sa.Integer(), nullable=True),
    sa.Column('last_reset', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_device_id'), 'users', ['device_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_device_id'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_tailor_sessions_user_id'), table_name='tailor_sessions')
    op.drop_table('tailor_sessions')
    # ### end Alembic commands ###
